name: Email Step Test

on:
  push:
    branches:
      - main  # or "master" if you're using that

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 24f1002302@ds.study.iitm.ac.in
        run: echo "Hello, world from IITM email step!"
